apiVersion: v1
entries:
  wind-river-cloud-platform-deployment-manager:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2025-12-19T15:34:21.309869772-03:00"
    description: A Helm chart for the Deployment Manager
    digest: 2884bcd884364fed70e9ef2aca5ec628e2f7d1e767163773a9f2d0931a22c5c5
    icon: https://www.windriver.com/resources/images/wr-logo-red-2018.png
    name: wind-river-cloud-platform-deployment-manager
    urls:
    - wind-river-cloud-platform-deployment-manager-26.03.0.tgz
    version: 26.03.0
generated: "2025-12-19T15:34:21.308978144-03:00"
