apiVersion: v1
entries:
  wind-river-cloud-platform-deployment-manager:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2025-11-25T13:49:13.982718851-05:00"
    description: A Helm chart for the Deployment Manager
    digest: 3ccfa807eb0e184b3d92dabe26358b11d4fde011aaa5202c9ae3d0d25b2fa7ce
    icon: https://www.windriver.com/resources/images/wr-logo-red-2018.png
    name: wind-river-cloud-platform-deployment-manager
    urls:
    - wind-river-cloud-platform-deployment-manager-25.09.0.tgz
    version: 25.09.0
generated: "2025-11-25T13:49:13.978987093-05:00"
