apiVersion: v1
entries:
  wind-river-cloud-platform-deployment-manager:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2025-12-09T16:55:33.245689631-03:00"
    description: A Helm chart for the Deployment Manager
    digest: fa8dc68cea3f430414ba1cc6c8fab48b08be53da4f78a9b3cfa900accefcdfed
    icon: https://www.windriver.com/resources/images/wr-logo-red-2018.png
    name: wind-river-cloud-platform-deployment-manager
    urls:
    - wind-river-cloud-platform-deployment-manager-25.09.0.tgz
    version: 25.09.0
generated: "2025-12-09T16:55:33.244735272-03:00"
