apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
kind: ControllerManagerConfig
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: 0.0.0.0:8443
webhook:
  port: 9443
leaderElection:
  leaderElect: false
  resourceName: f28f85eb.windriver.com
