# SPDX-License-Identifier: Apache-2.0
# Copyright(c) 2019 Wind River Systems, Inc.
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: {{ .Values.namespace }}
---
apiVersion: v1
data:
{{- with .Values.manager.configmap }}
  config.yaml: |
{{ toYaml . | indent 10 }}
{{- end }}
kind: ConfigMap
metadata:
  name: {{ include "helm.name" . }}-config
  namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.name" . }}-webhook-server-secret
  namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: {{ include "helm.name" . }}-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 443
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
---
{{- if .Values.manager.debugger.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.name" . }}-delve-service
  namespace: {{ .Values.namespace }}
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  type: NodePort
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  ports:
    - name: delve
      port: 40000
      nodePort: {{ .Values.manager.debugger.port }}
{{ end }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: {{ include "helm.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  serviceName: {{ include "helm.name" . }}-service
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
      {{- if .Values.rbacProxy.enabled }}
      - args:
        - --secure-listen-address=0.0.0.0:{{ .Values.rbacProxy.port}}
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v={{ .Values.rbacProxy.logLevel }}
        image: {{ .Values.rbacProxy.image }}
        name: kube-rbac-proxy
        ports:
        - containerPort: {{ .Values.rbacProxy.port }}
          name: https
      {{- end }}
      - args:
        {{- if .Values.manager.debugger.enabled }}
        - /manager
        {{- end }}
        - --metrics-addr=127.0.0.1:8080
        - --alsologtostderr=true
        - --v={{ .Values.manager.logLevel }}
        command:
        {{- if .Values.manager.debugger.enabled }}
        - /dlv-wrapper.sh
        {{- else }}
        - /manager
        {{- end }}
        env:
        - name: WAIT
          value: {{ .Values.manager.debugger.wait | quote }}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SECRET_NAME
          value: {{ include "helm.name" . }}-webhook-server-secret
        image: {{ .Values.manager.image.repository}}:{{ if .Values.manager.debugger.enabled}}debug{{ else }}{{ .Values.manager.image.tag }}{{ end }}
        imagePullPolicy: {{ .Values.manager.image.pullPolicy }}
        name: manager
        ports:
        - containerPort: 9876
          name: webhook-server
          protocol: TCP
{{- with .Values.resources }}
        resources:
{{ toYaml . | indent 10 }}
{{- end }}
        volumeMounts:
        - mountPath: /tmp/cert
          name: cert
          readOnly: true
        - mountPath: /etc/manager
          name: config
      nodeSelector:
        kubernetes.io/hostname: controller-0
      terminationGracePeriodSeconds: 10
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
{{- end }}
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ include "helm.name" . }}-webhook-server-secret
      - configMap:
          name: {{ include "helm.name" . }}-config
        name: config