---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: platformnetworks.starlingx.windriver.com
spec:
  group: starlingx.windriver.com
  names:
    kind: PlatformNetwork
    listKind: PlatformNetworkList
    plural: platformnetworks
    singular: platformnetwork
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The platform network type.
      jsonPath: .spec.type
      name: type
      type: string
    - description: The platform network address subnet.
      jsonPath: .spec.subnet
      name: subnet
      type: string
    - description: The platform network address prefix.
      jsonPath: .spec.prefix
      name: prefix
      type: string
    - description: The current synchronization state.
      jsonPath: .status.inSync
      name: insync
      type: boolean
    - description: The current reconciliation state.
      jsonPath: .status.reconciled
      name: reconciled
      type: boolean
    name: v1
    schema:
      openAPIV3Schema:
        description: "PlatformNetwork defines the attributes that represent the network
          level attributes of a StarlingX system.  This is a composition of the following
          StarlingX API endpoints. \n https://docs.starlingx.io/api-ref/stx-config/api-ref-sysinv-v1-config.html#networks
          https://docs.starlingx.io/api-ref/stx-config/api-ref-sysinv-v1-config.html#address-pools"
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: PlatformNetworkSpec defines the desired state of PlatformNetwork
            properties:
              allocation:
                description: Allocation defines the allocation scheme details for
                  the network
                properties:
                  order:
                    description: Order defines whether host address are allocation
                      randomly or sequential from the available pool or addresses.
                    enum:
                    - sequential
                    - random
                    type: string
                  ranges:
                    description: Ranges defines the pools from which host addresses
                      are allocated.   If omitted addresses the entire network address
                      space is considered available.
                    items:
                      description: AllocationRange defines the start and end address
                        for an allocation range
                      properties:
                        end:
                          description: End defines the end of the address range (inclusively)
                          type: string
                        start:
                          description: Start defines the beginning of the address
                            range (inclusively)
                          type: string
                      required:
                      - end
                      - start
                      type: object
                    type: array
                  type:
                    description: Type defines whether network addresses are allocated
                      dynamically or statically.
                    enum:
                    - static
                    - dynamic
                    type: string
                required:
                - type
                type: object
              gateway:
                description: Gateway defines the nexthop gateway IP address if applicable
                type: string
              prefix:
                maximum: 128
                minimum: 1
                type: integer
              subnet:
                description: Subnet defines the IPv4 or IPv6 network address for the
                  network
                type: string
              type:
                description: Type defines the intended usage of the network
                enum:
                - mgmt
                - pxeboot
                - infra
                - oam
                - multicast
                - system-controller
                - cluster-host
                - cluster-pod
                - cluster-service
                - storage
                - admin
                - other
                type: string
            required:
            - allocation
            - prefix
            - subnet
            - type
            type: object
          status:
            description: PlatformNetworkStatus defines the observed state of PlatformNetwork
            properties:
              id:
                description: ID defines the system assigned unique identifier.  This
                  will only exist once this resource has been provisioned into the
                  system.
                type: string
              inSync:
                description: Defines whether the resource has been provisioned on
                  the target system.
                type: boolean
              poolUUID:
                description: PoolUUID defines the system assigned unique identifier
                  that is represents the networks underlying address pool resource.  This
                  will only exist once this resource has been provisioned into the
                  system.
                type: string
              reconciled:
                description: Reconciled defines whether the network has been successfully
                  reconciled at least once.  If further changes are made they will
                  be ignored by the reconciler.
                type: boolean
            required:
            - inSync
            - reconciled
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
