---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.12.1
  name: datanetworks.starlingx.windriver.com
spec:
  group: starlingx.windriver.com
  names:
    kind: DataNetwork
    listKind: DataNetworkList
    plural: datanetworks
    singular: datanetwork
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The data network encapsulation type.
      jsonPath: .spec.type
      name: type
      type: string
    - description: The current synchronization state.
      jsonPath: .status.inSync
      name: insync
      type: boolean
    - description: The current deploymentScope state.
      jsonPath: .status.deploymentScope
      name: scope
      type: string
    - description: The current reconciliation state.
      jsonPath: .status.reconciled
      name: reconciled
      type: boolean
    name: v1
    schema:
      openAPIV3Schema:
        description: "DataNetworks defines the attributes that represent the data
          network level attributes of a StarlingX system.  This is a composition of
          the following StarlingX API endpoints. \n https://docs.starlingx.io/api-ref/stx-config/api-ref-sysinv-v1-config.html#data-networks"
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: DataNetworkSpec defines the desired state of DataNetwork
            properties:
              description:
                description: Description defines a user define description which explains
                  the purpose of the data network.
                type: string
              mtu:
                description: MTU defines the maximum transmit unit for any virtual
                  network derived from this data network.
                maximum: 9216
                minimum: 576
                type: integer
              type:
                description: Type defines the encapsulation method used for the data
                  network.
                enum:
                - flat
                - vlan
                - vxlan
                type: string
              vxlan:
                description: VxLan defines VxLAN specific attributes for the data
                  network.
                properties:
                  endpointMode:
                    description: EndpointMode defines the endpoint port learning mode
                      for the data network network.  The dynamic mode allows the virtual
                      network to use multicast addressing when transmitting a packet
                      to an unknown endpoint to dynamically discover that node's VTEP
                      IP address.   The static mode requires that all VTEP IP addresses
                      be programmed into the virtual switch in advance and any packets
                      destined to an unknown endpoint are dropped.
                    enum:
                    - static
                    - dynamic
                    type: string
                  multicastGroup:
                    description: MulticastGroup defines the multicast IP address to
                      be used for the data network.
                    type: string
                  ttl:
                    description: TTL defines the time-to-live value to assign to the
                      data network.
                    maximum: 255
                    minimum: 1
                    type: integer
                  udpPortNumber:
                    description: UDPPortNumber defines the UDP protocol number to
                      be used for the data network.  The IANA or Legacy port number
                      values can be used.
                    enum:
                    - 4789
                    - 8472
                    type: integer
                type: object
            required:
            - type
            type: object
          status:
            description: DataNetworkStatus defines the observed state of DataNetwork
            properties:
              configurationUpdated:
                description: Value for configuration is updated or not
                type: boolean
              delta:
                description: Delta between final profile vs current configuration
                type: string
              deploymentScope:
                default: bootstrap
                description: DeploymentScope defines whether the resource has been
                  deployed on the initial setup or during an update.
                enum:
                - bootstrap
                - principal
                type: string
              id:
                description: ID defines the system assigned unique identifier.  This
                  will only exist once this resource has been provisioned into the
                  system.
                type: string
              inSync:
                description: Defines whether the resource has been provisioned on
                  the target system.
                type: boolean
              observedGeneration:
                description: Reflect value of configuration generation. The value
                  will be set when configuration generation is updated.
                format: int64
                type: integer
              reconciled:
                description: Reconciled defines whether the host has been successfully
                  reconciled at least once.  If further changes are made they will
                  be ignored by the reconciler.
                type: boolean
              strategyRequired:
                default: not_required
                description: Value for configuration is updated or not
                enum:
                - not_required
                - lock_required
                - unlock_required
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
